"""Property-based test: decorated tools behave identically to the base
decorator.

The Strands and CrewAI ``cached_tool`` wrappers
(:mod:`memory_reuse.integrations.strands` /
:mod:`memory_reuse.integrations.crewai`) are thin parity layers over the shared
:func:`memory_reuse.integrations.langgraph.cached_tool` machinery. This test
compares each wrapper against that base decorator and asserts identical return
values and identical hit/miss (body-execution) behaviour, identical scope
handling (including :exc:`~memory_reuse.exceptions.ScopeViolationError` on an
unresolvable non-global scope), and identical exact-vs-semantic routing
(observed via an embed-call counter).

Uses the deterministic :class:`~tests.conftest.StubTool` (with a body-call
counter), the embed-call-counting :class:`~tests.conftest.StubEmbedder`, and the
``tool_arguments`` strategy from ``tests/conftest.py``; no real LLM, network, or
AWS is involved.

Neither ``strands`` nor ``crewai`` is installed in the test environment, so the
lazy dependency guards (``_require_strands`` / ``_require_crewai``) are patched
to no-ops via :func:`unittest.mock.patch.object` context managers *inside* the
test body — never a function-scoped fixture — so the patch stays correct across
every input generated by ``@given`` without tripping Hypothesis' health check.
The wrappers then delegate to the base decorator exactly as they would with the
dependency present, which is precisely the parity behaviour under test.

* **Property 12 — Decorated tools behave identically to the base decorator:**
  for any generated tool argument set and any (``scope``, ``semantic``,
  ``exact_only``) configuration, replaying a decorated call through the Strands
  or CrewAI wrapper yields the same return values, the same hit/miss behaviour
  (observed via the tool body-call counter), the same scope handling, and the
  same exact-vs-semantic routing as the base LangGraph decorator.
"""

# Feature: analytics-and-integrations, Property 12

from __future__ import annotations

import contextlib
from collections.abc import Callable, Iterator
from typing import Any, Literal

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from memory_reuse.exceptions import ScopeViolationError
from memory_reuse.integrations import crewai as crewai_integration
from memory_reuse.integrations import strands as strands_integration
from memory_reuse.integrations.langgraph import cached_tool as base_cached_tool
from tests.conftest import StubEmbedder, StubTool, make_tool_cache, tool_arguments

# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

# The (semantic, exact_only) configurations to compare across wrappers. The two
# flags are never both True: CrewAI rejects that combination at decoration time,
# so it is not a valid parity input.
_Config = tuple[bool, bool]
_configs: st.SearchStrategy[_Config] = st.sampled_from(
    [(False, False), (True, False), (False, True)]
)

_Scope = Literal["global", "user", "session"]
_scopes: st.SearchStrategy[_Scope] = st.sampled_from(["global", "user", "session"])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@contextlib.contextmanager
def _delegating_guards() -> Iterator[None]:
    """Neutralise both lazy dependency guards for the duration of the block.

    ``strands`` / ``crewai`` are not installed, so ``_require_strands`` /
    ``_require_crewai`` would raise
    :exc:`~memory_reuse.exceptions.BackendNotAvailableError`. Patching them to
    no-ops lets both wrappers reach the shared LangGraph machinery — the parity
    path under test — exactly as they would with the dependencies present. Using
    a context manager (not a function-scoped fixture) keeps the patch correct
    across every input generated by ``@given``.
    """
    from unittest import mock

    with (
        mock.patch.object(strands_integration, "_require_strands", lambda: None),
        mock.patch.object(crewai_integration, "_require_crewai", lambda: None),
    ):
        yield


def _make_tool() -> StubTool:
    """A fresh deterministic stub tool over a stable ``**kwargs`` signature."""

    def body(**kwargs: object) -> str:
        return f"result::{sorted(kwargs.items(), key=lambda kv: kv[0])}"

    return StubTool(result_fn=body)


def _decorate(
    factory: Callable[..., Callable],
    cache: Any,
    tool: StubTool,
    *,
    scope: _Scope,
    semantic: bool,
    exact_only: bool,
    scope_params: bool = True,
) -> Callable:
    """Apply a ``cached_tool`` factory to the stub tool under a fixed name.

    All three factories share one signature, so the only difference between the
    produced wrappers is the delegation path — exactly what the property
    compares. The wrapped body keeps a stable name so the derived cache key is
    identical across wrappers.

    When ``scope_params`` is ``True`` the body declares ``user_id`` /
    ``session_id`` as explicit parameters (not folded into ``**kwargs``) so the
    shared ``cached_tool`` scope resolution — which binds the call signature and
    looks for a top-level ``user_id`` / ``session_id`` — can find them, mirroring
    how a real scoped tool is written. When ``False`` the body accepts only
    ``**kwargs``, so a non-global scope has no id to resolve and must raise
    :exc:`~memory_reuse.exceptions.ScopeViolationError`.
    """
    if scope_params:

        async def parity_tool(
            *, user_id: object = None, session_id: object = None, **kwargs: object
        ) -> object:
            return tool.run(user_id=user_id, session_id=session_id, **kwargs)

    else:

        async def parity_tool(  # type: ignore[misc]
            **kwargs: object,
        ) -> object:
            return tool.run(**kwargs)

    return factory(
        cache,
        scope=scope,
        ttl=300,
        semantic=semantic,
        exact_only=exact_only,
    )(parity_tool)


def _scoped_kwargs(scope: _Scope, args: dict[str, object]) -> dict[str, object]:
    """Return ``args`` augmented with the scope id the given scope requires."""
    if scope == "global":
        return dict(args)
    field = "user_id" if scope == "user" else "session_id"
    return {**args, field: "scope-42"}


_FACTORIES = (
    base_cached_tool,
    strands_integration.cached_tool,
    crewai_integration.cached_tool,
)


# ---------------------------------------------------------------------------
# Property 12: Decorated tools behave identically to the base decorator
# ---------------------------------------------------------------------------


class TestProperty12DecoratorParity:
    """Feature: analytics-and-integrations, Property 12.

    Decorated tools behave identically to the base decorator.

    Validates: Requirements 6.5, 6.9, 6.10, 6.12, 7.5, 7.6, 7.7, 7.12
    """

    @settings(max_examples=100, deadline=None)
    @given(args=tool_arguments, scope=_scopes, config=_configs)
    async def test_wrappers_match_base_on_miss_then_hit(
        self,
        args: dict[str, object],
        scope: _Scope,
        config: _Config,
    ) -> None:
        """Strands/CrewAI replay a miss-then-hit exactly like the base decorator.

        For each decorator (base LangGraph, Strands, CrewAI) built over its own
        fresh cache and stub tool, the first call misses — it runs the body once
        and stores the result (Req 6.5) — and a second call with an equal
        argument set hits, returning the stored value with the body not re-run
        (Req 6.9/6.10 routing, 7.6/7.7). Every wrapper must agree with the base
        decorator on the returned values and on the body-call counts, proving the
        wrappers reuse the shared primitives unchanged (Req 6.12, 7.12).
        """
        semantic, exact_only = config

        with _delegating_guards():
            results: list[tuple[object, object, int]] = []
            for factory in _FACTORIES:
                embedder = StubEmbedder() if semantic else None
                cache = make_tool_cache(embedder=embedder)
                tool = _make_tool()
                decorated = _decorate(
                    factory,
                    cache,
                    tool,
                    scope=scope,
                    semantic=semantic,
                    exact_only=exact_only,
                )

                call_kwargs = _scoped_kwargs(scope, args)

                # First call: miss -> body runs once and result is stored.
                first = await decorated(**call_kwargs)
                assert tool.calls == 1

                # Second call with an equal argument set: hit -> body not re-run.
                second = await decorated(**dict(call_kwargs))
                assert tool.calls == 1
                assert second == first

                results.append((first, second, tool.calls))

            # Every wrapper agrees with the base decorator on values and counts.
            base_result = results[0]
            for other in results[1:]:
                assert other == base_result

    @settings(max_examples=100, deadline=None)
    @given(args=tool_arguments, config=_configs)
    async def test_wrappers_match_base_on_scope_violation(
        self,
        args: dict[str, object],
        config: _Config,
    ) -> None:
        """A missing non-global scope id raises identically and runs no body.

        With a ``user`` scope and no ``user_id`` resolvable from the arguments or
        the cache context, every wrapper must raise
        :exc:`~memory_reuse.exceptions.ScopeViolationError` and leave the tool
        body unexecuted, matching the base decorator's scope resolution (Req 7.5
        and the shared scope handling behind Req 6.x).
        """
        semantic, exact_only = config

        # Ensure no scope id leaks in via the generated arguments.
        clean_args = {k: v for k, v in args.items() if k not in ("user_id", "session_id")}

        with _delegating_guards():
            for factory in _FACTORIES:
                embedder = StubEmbedder() if semantic else None
                cache = make_tool_cache(embedder=embedder)
                tool = _make_tool()
                decorated = _decorate(
                    factory,
                    cache,
                    tool,
                    scope="user",
                    semantic=semantic,
                    exact_only=exact_only,
                    scope_params=False,
                )

                with pytest.raises(ScopeViolationError):
                    await decorated(**clean_args)

                # Scope check happens before the body: nothing ran.
                assert tool.calls == 0

    @settings(max_examples=100, deadline=None)
    @given(args=tool_arguments)
    async def test_exact_only_never_embeds_across_wrappers(
        self,
        args: dict[str, object],
    ) -> None:
        """An ``exact_only`` wrapper never embeds, matching the base decorator.

        Semantic matching is enabled on each cache, but every wrapper forces
        exact-only routing, so no wrapper ever invokes the embedder across a miss
        followed by an exact hit — the shared exact-vs-semantic routing (Req
        6.10, 7.7) is preserved by delegation (Req 6.12, 7.12).
        """
        with _delegating_guards():
            for factory in _FACTORIES:
                embedder = StubEmbedder()
                cache = make_tool_cache(embedder=embedder)
                tool = _make_tool()
                decorated = _decorate(
                    factory,
                    cache,
                    tool,
                    scope="global",
                    semantic=False,
                    exact_only=True,
                )

                await decorated(**args)  # miss
                await decorated(**dict(args))  # exact hit

                assert tool.calls == 1  # exactly one real run
                assert embedder.embed_calls == 0  # never embedded on exact path
