"""Property-based test: decorated tool store-and-replay round trip.

Exercises the Strands and CrewAI ``cached_tool`` wrappers
(:mod:`memory_reuse.integrations.strands` /
:mod:`memory_reuse.integrations.crewai`), which are thin parity layers over the
shared :func:`memory_reuse.integrations.langgraph.cached_tool` machinery. Uses
the deterministic :class:`~tests.conftest.StubTool` (with a per-call execution
counter) and :func:`~tests.conftest.make_tool_cache` from ``tests/conftest.py``;
no real LLM, network, or AWS is involved.

Neither ``strands`` nor ``crewai`` is installed in the test environment, so the
lazy dependency guards (``_require_strands`` / ``_require_crewai``) are
monkeypatched to no-ops. The wrapper then delegates to the base decorator
exactly as it would with the dependency present, which is precisely the store /
replay behaviour under test.

* **Property 11 — Decorated tool store-and-replay round trip (Strands &
  CrewAI):** for any tool arguments, calling a decorated tool twice with the
  same arguments executes the tool body exactly once (miss stores the result)
  and returns the stored value on the second call (hit) without re-running the
  body, with the replayed value equal to the one produced on the first call.
"""

# Feature: analytics-and-integrations, Property 11

from __future__ import annotations

from unittest import mock

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from memory_reuse.integrations import crewai as crewai_integration
from memory_reuse.integrations import strands as strands_integration
from tests.conftest import StubTool, make_tool_cache, tool_arguments

# The two parity wrappers under test, each paired with the name of the lazy
# dependency guard that must be neutralised so the wrapper can delegate.
_WRAPPERS = [
    pytest.param(strands_integration, "_require_strands", id="strands"),
    pytest.param(crewai_integration, "_require_crewai", id="crewai"),
]


class TestProperty11DecoratedToolStoreAndReplayRoundTrip:
    """Feature: analytics-and-integrations, Property 11.

    Decorated tool store-and-replay round trip (Strands & CrewAI).

    Validates: Requirements 6.1, 6.4, 6.5, 7.1, 7.3, 7.4
    """

    @settings(max_examples=100)
    @given(kwargs=tool_arguments, use_async=st.booleans())
    @pytest.mark.parametrize("module, guard_name", _WRAPPERS)
    async def test_store_then_replay_round_trip(
        self,
        module: object,
        guard_name: str,
        kwargs: dict,
        use_async: bool,
    ) -> None:
        """Two identical calls run the body once then zero times, same result.

        The first call misses: no entry exists for the argument-derived key, so
        the tool body runs exactly once and the returned value is stored under
        that key (Req 6.5, 7.4). The second call with equal arguments hits: the
        stored value is returned without re-running the body (Req 6.1, 6.4, 7.1,
        7.3), and it equals the value produced and stored on the first call.
        """
        # Neutralise the lazy dependency guard so the wrapper delegates exactly
        # as it would with strands/crewai installed (neither is present here).
        # A context manager (not a function-scoped fixture) keeps the patch
        # correct across every input generated by ``@given``.
        with mock.patch.object(module, guard_name, lambda: None):
            # Fresh cache + tool per example so the first call is a sure miss.
            cache = make_tool_cache()
            tool = StubTool()
            body = tool.arun if use_async else tool.run

            decorated = module.cached_tool(cache)(body)

            # First call: miss -> runs the body once and stores the result.
            first = await decorated(**kwargs)
            assert tool.calls == 1

            # Second call with equal arguments: hit -> body does not re-run.
            second = await decorated(**dict(kwargs))
            assert tool.calls == 1

            # The replayed value equals the one produced and stored on the miss.
            assert second == first
