"""Configuration dataclass for the memory-reuse."""

from __future__ import annotations

import os
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from memory_reuse.analytics.pricing import PricingConfig


@dataclass
class CacheConfig:
    """Configuration for the MemoryCache.

    All values can be overridden via environment variables when using
    :meth:`MemoryCache.from_env`.

    Attributes:
        backend: Storage backend to use. ``"memory"`` requires no extra
            dependencies; ``"redis"`` requires ``pip install memory-reuse[redis]``;
            ``"agentcore"`` requires ``pip install memory-reuse[agentcore]``.
        redis_url: Connection URL for the Redis backend. Should be supplied
            via the ``MEMORY_REUSE_REDIS_URL`` environment variable rather
            than hardcoded.
        agentcore_region: AWS region hosting the AgentCore store. Used only
            when ``backend="agentcore"``.
        agentcore_memory_id: AgentCore memory / store resource identifier.
            Used only when ``backend="agentcore"``.
        default_ttl: Default time-to-live in seconds for cached entries.
            ``None`` means entries never expire.
        default_scope: Default cache scope applied when no explicit scope is
            passed to cache operations.
        key_prefix: String prepended to every cache key for namespacing.
        max_key_size: Maximum allowed cache-key length in bytes. Requests
            that would produce a longer key raise ``ValueError``.
        enable_stats: When ``True``, hit/miss/error counts are tracked and
            accessible via :attr:`MemoryCache.stats`.
        semantic_enabled: When ``True``, the semantic (similarity-based) cache
            is enabled in addition to the exact cache. Off by default so
            existing behaviour is unchanged; requires ``embedding_provider``.
        similarity_threshold: Minimum cosine similarity (normalised to
            ``[0.0, 1.0]``) at which two requests are treated as the same and a
            cached result is reused. Higher values favour precision over recall.
        embedding_provider: Which embedding provider to use for semantic
            lookups. ``None`` disables provider selection; required when
            ``semantic_enabled`` is ``True``.
        embedding_model: Optional model name passed to the embedding provider.
            ``None`` lets the provider pick its default model.
        max_vectors_per_namespace: Maximum number of stored vectors per scope
            namespace before LRU eviction applies.
        store_exact_on_semantic_hit: When ``True``, a semantic hit also writes
            an exact-match entry so the next identical request hits the faster
            exact path.
        extract_answer: When ``True`` (and the cached value is a string), a
            semantic hit returns only the sentence(s) of the stored answer that
            best match the query, rather than the whole answer. This is a purely
            *extractive*, embedding-based narrowing — no LLM call and no
            generation — so it can only return text already present in the
            stored answer. Off by default; the core cache returns values
            verbatim.
        extract_min_similarity: Minimum normalised cosine similarity
            (``[0.0, 1.0]``) a sentence must reach against the query for
            :attr:`extract_answer` to return just that sentence. When no
            sentence clears this bar the full stored answer is returned, so
            extraction never yields an empty result.
        pricing: Optional per-token
            :class:`~memory_reuse.analytics.pricing.PricingConfig` used by the
            analytics layer to compute cost saved from tokens saved. ``None``
            (the default) means cost is not tracked; token and latency savings
            are still tracked. Set in code, not via an environment variable.
        cache_version: Optional version token folded into every cache key so a
            redeploy with updated prompts, models, or tools never reuses a result
            generated by an incompatible older version. ``None`` (the default)
            keeps keys byte-identical to a pre-Phase-6 config, so existing cached
            entries continue to hit after upgrading. A version change invalidates
            reuse uniformly across the exact, tool, and semantic layers.
        single_flight: When ``True``, :meth:`MemoryCache.get_or_compute`
            coalesces concurrent misses for the same key so the expensive compute
            runs once and its result is shared. ``False`` (the default) leaves
            every existing cache operation unchanged.
        distributed_lock: When ``True``, single-flight coordination extends
            across processes with a per-key Redis lock (requires the Redis
            backend). Off by default; enabling it without a Redis backend raises
            a configuration error at construction.
        max_tracked_operations: Maximum number of distinct operation aggregates
            the effectiveness analyzer retains, bounding its memory use. Once
            reached, observations for new operations are dropped.
        serializer: Optional callable converting a value into a JSON-native
            representation before storage. Paired with ``deserializer`` for a
            faithful round-trip of framework objects (e.g. LangChain messages).
            ``None`` (the default) stores values exactly as before.
        deserializer: Optional callable reconstructing the original value from
            its JSON-native representation on load. Must be paired with
            ``serializer``. ``None`` (the default) returns parsed JSON as-is.

    Example::

        config = CacheConfig(
            backend="redis",
            redis_url=os.environ["REDIS_URL"],
            default_ttl=600,
            default_scope="user",
        )
    """

    backend: Literal["memory", "redis", "agentcore"] = "memory"
    redis_url: str | None = None
    default_ttl: int | None = 3600
    default_scope: Literal["global", "user", "session"] = "global"
    key_prefix: str = "memreuse"
    max_key_size: int = 512
    enable_stats: bool = True
    semantic_enabled: bool = False
    similarity_threshold: float = 0.95
    embedding_provider: Literal["openai", "local", "litellm"] | None = None
    embedding_model: str | None = None
    max_vectors_per_namespace: int = 10_000
    store_exact_on_semantic_hit: bool = True
    extract_answer: bool = False
    extract_min_similarity: float = 0.5
    # Phase 4 (additive): AgentCore connection settings, used only when
    # ``backend="agentcore"``. Left at their defaults, behaviour is identical
    # to a pre-Phase-4 config (Req 11.3).
    agentcore_region: str | None = None
    agentcore_memory_id: str | None = None
    # Phase 5 (additive): optional per-token pricing used to compute cost saved
    # in the analytics layer. ``None`` means cost is not tracked (token and
    # latency savings still are). Left at its default, behaviour is identical to
    # a pre-Phase-5 config. This is a structured object, so it is set in code
    # rather than via an environment variable; ``from_env`` does not read it.
    pricing: PricingConfig | None = None
    # Phase 6 (additive): optional cache-version token folded into every cache
    # key so a redeploy with new prompts/models/tools never serves a result
    # generated by incompatible older logic. ``None`` (the default) leaves keys
    # byte-identical to a pre-Phase-6 config, so existing entries keep hitting.
    cache_version: str | None = None
    # Phase 6 (additive): opt-in single-flight coalescing of concurrent misses.
    # ``False`` (the default) leaves every cache operation behaving as before;
    # when ``True``, ``MemoryCache.get_or_compute`` coalesces concurrent misses
    # for the same key so the expensive compute runs once.
    single_flight: bool = False
    # Phase 6 (additive): extend single-flight coalescing across processes with a
    # per-key Redis lock. Requires the Redis backend; validated at construction.
    distributed_lock: bool = False
    # Phase 6 (additive): cap on the number of distinct operation aggregates the
    # effectiveness analyzer retains, bounding its memory use.
    max_tracked_operations: int = 1000
    # Phase 6 (additive): optional (de)serialization hooks applied around the
    # gzip/JSON storage step so framework objects (e.g. LangChain messages)
    # round-trip faithfully. Both ``None`` (the default) => byte-identical to a
    # pre-Phase-6 config. Supply the paired hooks together (e.g. via
    # ``memory_reuse.integrations.langchain_serde.langchain_message_codec()``).
    serializer: Callable[[Any], Any] | None = None
    deserializer: Callable[[Any], Any] | None = None

    def __post_init__(self) -> None:
        """Validate the configuration after initialisation."""
        if self.backend not in {"memory", "redis", "agentcore"}:
            from memory_reuse.exceptions import ConfigurationError

            raise ConfigurationError(
                f"Unknown backend '{self.backend}'. "
                "Supported values: 'memory', 'redis', 'agentcore'."
            )
        if self.default_ttl is not None and self.default_ttl <= 0:
            from memory_reuse.exceptions import InvalidTTLError

            raise InvalidTTLError(
                f"default_ttl must be a positive integer or None, got {self.default_ttl}"
            )
        if self.max_key_size <= 0:
            raise ValueError(f"max_key_size must be positive, got {self.max_key_size}")
        if not 0.0 <= self.similarity_threshold <= 1.0:
            from memory_reuse.exceptions import ConfigurationError

            raise ConfigurationError(
                "similarity_threshold must be within [0.0, 1.0], "
                f"got {self.similarity_threshold}"
            )
        if not 0.0 <= self.extract_min_similarity <= 1.0:
            from memory_reuse.exceptions import ConfigurationError

            raise ConfigurationError(
                "extract_min_similarity must be within [0.0, 1.0], "
                f"got {self.extract_min_similarity}"
            )
        if self.semantic_enabled and self.embedding_provider is None:
            from memory_reuse.exceptions import ConfigurationError

            raise ConfigurationError(
                "semantic_enabled=True requires an embedding_provider "
                "(one of 'openai', 'local', 'litellm')"
            )
        if self.cache_version is not None and not isinstance(self.cache_version, str):
            from memory_reuse.exceptions import ConfigurationError

            raise ConfigurationError(
                f"cache_version must be a string or None, got {self.cache_version!r}"
            )

    @classmethod
    def from_env(cls) -> CacheConfig:
        """Create a :class:`CacheConfig` from ``MEMORY_REUSE_*`` environment variables.

        Recognised variables:

        * ``MEMORY_REUSE_BACKEND`` — ``"memory"``, ``"redis"``, or ``"agentcore"``
        * ``MEMORY_REUSE_REDIS_URL`` — Redis connection URL
        * ``MEMORY_REUSE_AGENTCORE_REGION`` — AWS region hosting the AgentCore
          store (required when ``backend="agentcore"``)
        * ``MEMORY_REUSE_AGENTCORE_MEMORY_ID`` — AgentCore memory / store resource
          identifier (required when ``backend="agentcore"``)
        * ``MEMORY_REUSE_DEFAULT_TTL`` — integer seconds or ``"none"``
        * ``MEMORY_REUSE_DEFAULT_SCOPE`` — ``"global"``, ``"user"``, or ``"session"``
        * ``MEMORY_REUSE_KEY_PREFIX`` — string prefix for all keys
        * ``MEMORY_REUSE_ENABLE_STATS`` — ``"true"`` / ``"false"``
        * ``MEMORY_REUSE_SEMANTIC_ENABLED`` — ``"true"`` / ``"false"``
        * ``MEMORY_REUSE_SIMILARITY_THRESHOLD`` — float in ``[0.0, 1.0]``
        * ``MEMORY_REUSE_EMBEDDING_PROVIDER`` — ``"openai"``, ``"local"``, or ``"litellm"``
        * ``MEMORY_REUSE_EMBEDDING_MODEL`` — embedding model name

        Returns:
            A :class:`CacheConfig` populated from the environment.

        Raises:
            ConfigurationError: If ``backend="agentcore"`` is selected but a
                required AgentCore connection setting
                (``MEMORY_REUSE_AGENTCORE_REGION`` or
                ``MEMORY_REUSE_AGENTCORE_MEMORY_ID``) is absent.
        """
        raw_ttl = os.environ.get("MEMORY_REUSE_DEFAULT_TTL")
        if raw_ttl is None:
            default_ttl: int | None = 3600
        elif raw_ttl.lower() == "none":
            default_ttl = None
        else:
            default_ttl = int(raw_ttl)

        raw_stats = os.environ.get("MEMORY_REUSE_ENABLE_STATS", "true")
        enable_stats = raw_stats.lower() not in {"false", "0", "no"}

        backend = os.environ.get("MEMORY_REUSE_BACKEND", "memory")
        scope = os.environ.get("MEMORY_REUSE_DEFAULT_SCOPE", "global")

        raw_semantic = os.environ.get("MEMORY_REUSE_SEMANTIC_ENABLED", "false")
        semantic_enabled = raw_semantic.lower() in {"true", "1", "yes"}

        raw_threshold = os.environ.get("MEMORY_REUSE_SIMILARITY_THRESHOLD")
        similarity_threshold = 0.95 if raw_threshold is None else float(raw_threshold)

        embedding_provider = os.environ.get("MEMORY_REUSE_EMBEDDING_PROVIDER")

        agentcore_region = os.environ.get("MEMORY_REUSE_AGENTCORE_REGION")
        agentcore_memory_id = os.environ.get("MEMORY_REUSE_AGENTCORE_MEMORY_ID")

        if backend == "agentcore":
            from memory_reuse.exceptions import ConfigurationError

            if not agentcore_region:
                raise ConfigurationError(
                    "backend='agentcore' requires MEMORY_REUSE_AGENTCORE_REGION to be set."
                )
            if not agentcore_memory_id:
                raise ConfigurationError(
                    "backend='agentcore' requires MEMORY_REUSE_AGENTCORE_MEMORY_ID to be set."
                )

        return cls(
            backend=backend,  # type: ignore[arg-type]
            redis_url=os.environ.get("MEMORY_REUSE_REDIS_URL"),
            agentcore_region=agentcore_region,
            agentcore_memory_id=agentcore_memory_id,
            default_ttl=default_ttl,
            default_scope=scope,  # type: ignore[arg-type]
            key_prefix=os.environ.get("MEMORY_REUSE_KEY_PREFIX", "memreuse"),
            enable_stats=enable_stats,
            semantic_enabled=semantic_enabled,
            similarity_threshold=similarity_threshold,
            embedding_provider=embedding_provider,  # type: ignore[arg-type]
            embedding_model=os.environ.get("MEMORY_REUSE_EMBEDDING_MODEL"),
        )
